version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: hiyasichuka/atcoder:dev
    volumes:
      - ../problems:/root/problems:cached
      - ../library:/root/library:cached
      - ../acc-template-python:/root/.config/atcoder-cli-nodejs/python:cached
      - ../.vscode:/root/.vscode:cached

    command: /bin/sh -c "while sleep 1000; do :; done"